### PR TITLE
fixed release version

### PR DESCRIPTION
**Pull request by Yom3n**
Downgraded android-pdf-viever to 2.8.2

### CODE REVIEW

**Comment by KipCrossing** [comment]
Whats the status on this? Thanks!

**Comment by king-millez** [comment]
Hey man, I got a lot on the line waiting for this PR to be merged. Boss is on my back every day wanting to see his PDFs in app. If you could merge this my life will become bearable and I'll be able to see my family again.

**Comment by KipCrossing** [comment]
@lubritto  Going to bum this PR

**Comment by mdmota** [comment]
```
Running Gradle task 'assembleDevDebug'...
C:\flutter\.pub-cache\hosted\pub.dartlang.org\pdf_viewer_plugin-1.0.1\android\src\main\java\com\example\pdfviewerplugin\PdfViewer.java:25: error: cannot find symbol
        Intent i = new Intent(this, Wakeup.class);
        ^
  symbol:   class Intent
  location: class PdfViewer
C:\flutter\.pub-cache\hosted\pub.dartlang.org\pdf_viewer_plugin-1.0.1\android\src\main\java\com\example\pdfviewerplugin\PdfViewer.java:25: error: cannot find symbol
        Intent i = new Intent(this, Wakeup.class);
                       ^
  symbol:   class Intent
  location: class PdfViewer
C:\flutter\.pub-cache\hosted\pub.dartlang.org\pdf_viewer_plugin-1.0.1\android\src\main\java\com\example\pdfviewerplugin\PdfViewer.java:25: error: cannot find symbol
        Intent i = new Intent(this, Wakeup.class);
                                    ^
  symbol:   class Wakeup
  location: class PdfViewer
C:\flutter\.pub-cache\hosted\pub.dartlang.org\pdf_viewer_plugin-1.0.1\android\src\main\java\com\example\pdfviewerplugin\PdfViewer.java:26: error: cannot find symbol
        i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                   ^
  symbol:   variable Intent
  location: class PdfViewer
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pdf_viewer_plugin:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Exception: Gradle task assembleDevDebug failed with exit code 1
```

**Comment by mdmota** [comment]
error when upgrading to the latest version

**Pull request merged**
